project:
  type: website

website:
  title: "Null ritual"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: slides/index.qmd
        text: Slides

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true



