---
title: "Mindless statistics and the 'null ritual'"
author: "Dr Stefano Coretta"
institute: "University of Edinburgh"
date: "2025/05/01"
format: 
  mono-light-revealjs:
    theme: [default, "custom.scss"]
    history: false
    fig-align: center
filters:
  - tachyonsextra
execute: 
  echo: false
  fig-align: center
bibliography: references.bib
csl: unified-style-sheet-for-linguistics.csl
---

```{r}
#| label: setup
#| include: false

library(tidyverse)
theme_set(theme_light())
```

## Quiz

::: box-tip
Suppose you have a treatment that you suspect may alter performance on a certain task. You compare the means of your control and experimental groups (say 20 subjects in each sample). Further, suppose you use a simple independent means t-test and your result is signiﬁcant (t = 2.7, d.f. = 18, p = 0.01).

1.  You have absolutely disproved the null hypothesis (that is, there is no difference between the population means).

2.  You have found the probability of the null hypothesis being true.

3.  You have absolutely proved your experimental hypothesis (that there is a difference between the population means).

4.  You can deduce the probability of the experimental hypothesis being true.

5.  You know, if you decide to reject the null hypothesis, the probability that you are making the wrong decision.

6.  You have a reliable experimental ﬁnding in the sense that if, hypothetically, the experiment were repeated a great number of times, you would obtain a signiﬁcant result on 99% of occasions.
:::

## True or false?

```{=html}
<iframe allowfullscreen frameborder="0" height="100%" mozallowfullscreen style="min-width: 500px; min-height: 355px" src="https://app.wooclap.com/events/DLCGFB/questions/67ee52eeb1a525d6d1d98282" width="100%"></iframe>
```

## The 'null ritual'

::: box-tip
@gigerenzer2004, @gigerenzer2004a, @gigerenzer2018.

1.  Set up a statistical null hypothesis of "no mean difference" or "zero correlation." Don't specify the predictions of your research hypothesis or of any alternative substantive hypotheses.

2.  Use 5% as a convention for rejecting the null. If signiﬁcant, accept your research hypothesis. Report the result as p \< 0.05, p \< 0.01, or p \< 0.001 (whichever comes next to the obtained p-value).

3.  Always perform this procedure.
:::

## Why is it problematic?

::: box-error
The null ritual would have been rejected by the statisticians it is attributed to.

1.  **Fisher** rejected each of the steps above towards the end of his life.
    1.  "Null" does not mean "nil" but "to be nullified".
    2.  Fisher thought that using a routine 5% level of signiﬁcance indicated lack of statistical thinking.
    3.  Null hypothesis testing was the most primitive of analyses (only when no or very little knowledge.
2.  **Neyman and Pearson** rejected null hypothesis testing and favoured competitive testing between two or more hypotheses.
:::

## Fisher's null hypothesis testing

::: box-note
1.  Set up a statistical null hypothesis. The null need not be a nil hypothesis (i.e., zero difference).

2.  Report the exact level of signiﬁcance (e.g., p = 0.051 or p = 0.049). Do not use a conventional 5% level, and do not talk about accepting or rejecting hypotheses.

3.  Use this procedure only if you know very little about the problem at hand.

[@gigerenzer2004, pp. 590]
:::

## Neyman–Pearson decision theory

::: box-note
1.  Set up two statistical hypotheses, H1 and H2, and decide about $\alpha$, $\beta$, and sample size before the experiment, based on subjective cost-beneﬁt considerations. These deﬁne a rejection region for each hypothesis.
2.  If the data falls into the rejection region of H1, accept H2; otherwise accept H1. Note that accepting a hypothesis does not mean that you believe in it, but only that you act as if it were true.
3.  The usefulness of the procedure is limited among others to situations where you have a disjunction of hypotheses (e.g., either $\mu_1 = 8$ or $\mu_2 = 10$ is true) and where you can make meaningful cost-beneﬁt trade-offs for choosing alpha and beta.

[@gigerenzer2004, pp. 590-1]
:::

## References

::: {#refs}
:::
